spring:
  application:
    name: p2p-task


dubbo:
  application:
    name: task
  registry:
    address: zookeeper://localhost:2181
  scan:
    base-packages: com.bjpowernode.p2p
  consumer:
    check: false